// Generated by CoffeeScript 1.9.1
(function() {
  var GoogleNews, googleNews, indexPath, path, track;

  path = require('path');

  indexPath = path.join(__dirname, 'index.js');

  GoogleNews = require(indexPath);

  googleNews = new GoogleNews({
    pollInterval: 5000
  });

  track = 'Volvo';

  googleNews.stream(track, function(stream) {
    stream.on(GoogleNews.DATA, function(data) {
      return console.log('Data Event received... ' + data.title);
    });
    stream.on(GoogleNews.ERROR, function(error) {
      return console.log('Error Event received... ' + error);
    });
  });

}).call(this);

//# sourceMappingURL=demo.js.map
