// Generated by CoffeeScript 1.9.1
(function() {
  var assert, should;

  should = require("should");

  assert = require("assert");

  describe('GoogleNews', function() {

    /*GoogleNews = require('../index.js'); */

    /*describe '#constructor', () ->
      it 'should return a GoogleNews Object', () ->
        should.exist(GoogleNews)
     */
  });

}).call(this);

//# sourceMappingURL=GoogleNews.js.map
