// Generated by CoffeeScript 1.9.1
(function() {
  var assert, should;

  should = require("should");

  assert = require("assert");

  describe('GoogleNews', function() {
    var GoogleNews;
    GoogleNews = require('../index');
    return describe('#constructor', function() {
      return it('should return a GoogleNews Object', function() {
        return should.exist(GoogleNews);
      });
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
