// Generated by CoffeeScript 1.9.1
(function() {
  describe('My test', function() {
    it('should run synchronously', function() {});
    return it('should run asynchronously', function(next) {
      return next();
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
